### ISSUE TITLE
您有训练好的模型吗

### ISSUE THREAD

**Issue by wangbq18** [yeyupiaoling/Kersa-Speaker-Recognition#1]
您好，请问您有训练好的模型吗，博客上的链接失效了

**Comment by yeyupiaoling** [comment]
@wangbq18 没失效呢，可以下载，：https://resource.doiduoyi.com/#w0c5949
![image](https://user-images.githubusercontent.com/26297768/90599021-b2864500-e226-11ea-8f70-5fb7df9c8e98.png)

**Comment by wangbq18** [comment]
> @wangbq18 没失效呢，可以下载，：https://resource.doiduoyi.com/#c9yq536
> 我点击下载就跳到一张图片上https://s1.ax1x.com/2020/07/14/UUBZlV.jpg，没跳到下载的页面，不知道什么原因

**Comment by yeyupiaoling** [comment]
@wangbq18 不好意思，我上传错了，等下，我重新上传。

**Comment by wangbq18** [comment]
> @wangbq18 不好意思，我上传错了，等下，我重新上传。

感谢，期待！这个训练好的模型可以直接在这个项目上运行是吗

**Comment by yeyupiaoling** [comment]
@wangbq18 上传好了，地址：https://resource.doiduoyi.com/#w0c5949

**Comment by yeyupiaoling** [comment]
> 感谢，期待！这个训练好的模型可以直接在这个项目上运行是吗

是的，留意参数是`n_classes=5994，net=resnet34s，ghost_cluster=2，vlad_cluster=8，bottleneck_dim=512，aggregation_mode=gvlad，loss=softmax`

**Comment by wangbq18** [comment]
> > 感谢，期待！这个训练好的模型可以直接在这个项目上运行是吗
> 
> 是的，留意参数是`n_classes=5994，net=resnet34s，ghost_cluster=2，vlad_cluster=8，bottleneck_dim=512，aggregation_mode=gvlad，loss=softmax`

好的，期待您自己基于大数据集训练的模型！

**Comment by XuannLii** [comment]
您好，根据您的链接https://resource.doiduoyi.com/#w0c5949，没有找到相应的预训练模型，请问是失效了吗？

**Comment by wangbq18** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好!我已收到您的邮件！

**Comment by yeyupiaoling** [comment]
在项目主页下载 @Is-Sakura-i
