### ISSUE TITLE
librosa.util.exceptions.ParameterError: Audio buffer is not Fortran-contiguous.

### ISSUE THREAD

**Issue by wangbq18** [yeyupiaoling/Kersa-Speaker-Recognition#2]
您好，我用该项目跑ST-CMDS20170001_1和data_thchs30两个数据集，在执行create_data.py时，　data_thchs30数据集很多数据都显示＂音频错误，删除＂，我就跳过此步骤直接训练，然后就报错
librosa.util.exceptions.ParameterError: Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity.　这个怎么解决呢

**Comment by yeyupiaoling** [comment]
@wangbq18 你看看你的路径是否正确，打印一下删除的原因是什么。

**Comment by wangbq18** [comment]
> @wangbq18 你看看你的路径是否正确，打印一下删除的原因是什么。

我打印勒错误信息，是Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity.　不知道怎么解决

**Comment by yeyupiaoling** [comment]
@wangbq18  我说的不是训练，而是执行create_data.py时，提示＂音频错误，删除＂，

我修改代码，会打印出错误的原因，git pull 之后在试试

**Comment by wangbq18** [comment]
> @wangbq18 我说的不是训练，而是执行create_data.py时，提示＂音频错误，删除＂，
> 
> 我修改代码，会打印出错误的原因，git pull 之后在试试

感谢，我执行的是create_data.py 函数，打印了报错的信息，就是＂Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity＂，跟训练时的错是一样的

**Comment by yeyupiaoling** [comment]
@wangbq18 数量多吗？如果不多，那等他删除完，要git pull 最新的

**Comment by wangbq18** [comment]
> @wangbq18 数量多吗？如果不多，那等他删除完，要git pull 最新的

共12万多，2000个中删了600多

**Comment by yeyupiaoling** [comment]
@wangbq18 那不算多，这是正常的，删除错误的音频，训练就不会错误了，

**Comment by wangbq18** [comment]
> @wangbq18 那不算多，这是正常的，删除错误的音频，训练就不会错误了，

好的，非常感谢！我是怕数据都删了，训练数据不够，我目前只有两个数据集

**Comment by yeyupiaoling** [comment]
@wangbq18 VoxCeleb2数据集不用吗？这个数据集很大的

**Comment by wangbq18** [comment]
> @wangbq18 VoxCeleb2数据集不用吗？这个数据集很大的

没有下载下来，后期加上．多谢大佬！看了你很多项目，很赞！

**Comment by yeyupiaoling** [comment]
好的，也有很多公开的中文声纹识别语音数据集，可以试试，你机器强大吗？

**Comment by wangbq18** [comment]
> @wangbq18 VoxCeleb2数据集不用吗？这个数据集很大的

对了．大佬的网盘有数据集吗，能给个吗？数据下的很慢，我这边有V100服务器，集群

**Comment by wangbq18** [comment]
> 好的，也有很多公开的中文声纹识别语音数据集，可以试试，你机器强大吗？

如果有需要，我可以帮你训练

**Comment by yeyupiaoling** [comment]
@wangbq18 多卡也不行，IO跟不上，数据预处理没有没有使用多线程读取，比较忙，我现在单卡训练，GPU空闲的时间很多

**Comment by yeyupiaoling** [comment]
按照目前的速度，要训练一个月左右

**Comment by wangbq18** [comment]
> @wangbq18 多卡也不行，IO跟不上，数据预处理没有没有使用多线程读取，比较忙，我现在单卡训练，GPU空闲的时间很多
嗯嗯，后期可以改改

**Comment by yeyupiaoling** [comment]
嗯嗯，有时间看一下如何处理，也有可能是我的机器IO的问题。

**Comment by wangbq18** [comment]
> 嗯嗯，有时间看一下如何处理，也有可能是我的机器IO的问题。

对，跟图像任务训练类似，固态因盘可能会好点，对了，大佬网盘有VoxCeleb2数据集吗？

**Comment by yeyupiaoling** [comment]
我在这里下载的：https://blog.csdn.net/yj13811596648/article/details/97623551

**Comment by wangbq18** [comment]
> 我在这里下载的：https://blog.csdn.net/yj13811596648/article/details/97623551

老哥，请教你一下，这个声纹识别项目对说话人说的内容和录音时长有啥要求，说话内容需要一致吗？还有就是老哥自己的模型多久能放放出来啊，期待！

**Comment by yeyupiaoling** [comment]
@wangbq18 录音是16kHz的pcm音频就可以，录音时长2.5秒以上，一般是3秒，内容不需要一致。

我的训练模型估计要很久，别等了。

**Comment by xin-fight** [comment]
你好，请问你的官方的预训练模型是使用的什么数据集训练的？数据集有没有包含vox1

当我重新训练自己的模型的时候，我发现在train.py中，当要继续训练的时候，我发现每次都是还没有进入epoch就无错误退出了代码了，请问这是什么原因呢

**Comment by yeyupiaoling** [comment]
@xin-fight 我看源码官方的是只用vox2

你重新训练的的错误，是不是类似数量不对？看下日志

**Comment by xin-fight** [comment]
你好，请问是否有该代码官方的地址？我想去学习一下

**Comment by yeyupiaoling** [comment]
@xin-fight 文档的第一段就说了地址，你去看一下

**Comment by yeyupiaoling** [comment]
没有问题我就关闭issue了，有需要再提新的。
