### ISSUE TITLE
train.py出现EOFError: Ran out of input

### ISSUE THREAD

**Issue by InedibleMushrooms** [yeyupiaoling/Kersa-Speaker-Recognition#3]
大佬，我将cn-celeb数据创建好后，进行训练的时候出现了如下错误，貌似是多线程的问题，但是设置的参数明明是0

<img width="960" alt="Snipaste_2020-10-30_15-29-12" src="https://user-images.githubusercontent.com/59546276/97672378-eacabf00-1ac4-11eb-9ead-798cc7465c4d.png">

**Comment by yeyupiaoling** [comment]
@InedibleMushrooms 你拉下最新代码试试

**Comment by InedibleMushrooms** [comment]
好的
